### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by superpig** [kuitos/angular-es-utils#10]
![image](https://user-images.githubusercontent.com/5066518/29200885-bcb540aa-7e8b-11e7-8b6f-aa0a59665a16.png)

```js
import { Inject } from 'angular-es-utils';  
```
使用的时候报错，AngularJS版本为1.5.5

**Comment by kuitos** [comment]
没有安装 angular-resource 模块

**Comment by superpig** [comment]
@kuitos  安装angular-resource模块后问题解决了，另外angular-resource版本需要项目中AngularJS的版本一致。但不理解的是，为什么要单独安装angular-resource？如果存在这种问题是不是需要readme说明下

**Comment by kuitos** [comment]
rs-generator 依赖 angular-resource
版本已更新 2.1.5，将这个前置依赖代码移除了

**Comment by kuitos** [comment]
closed
