### ISSUE TITLE
关于装饰器 Inject 实现问题

### ISSUE THREAD

**Issue by hjzheng** [kuitos/angular-es-utils#7]
首先 Inject 的实现非常巧妙，解决了 AngularJS 1.x 的依赖注入，并且将依赖注入的服务，挂载到原构造函数的 prototype 上，方便使用。但是由于 Inject 装饰器返回了新的 class，导致一块使用的装饰器无法拿到原构造函数信息。另外 Inject 也不支持继承。

可以通过 Proxy 去装饰原构造函数而无需使用新 class 的方式。

```js
const toString = Object.prototype.toString;

export const Inject = (...dependencies) => (originTarget) => {

	// 获取当前 class 的父类
	const parentClass = Object.getPrototypeOf(originTarget);

	const parentDependencies = parentClass.$inject;

	if (parentDependencies && toString.call(parentDependencies) === '[object Array]') {
		dependencies = [...dependencies, ...parentDependencies];
	}

	originTarget.$inject = dependencies;

        // 使用 Proxy 修改构造函数
	const handler = {
		construct(target, argumentsList) {
			dependencies.forEach((dependence, index) => {
				target.prototype[`_${dependence}`] = argumentsList[index];
			});
			return Reflect.construct(target, argumentsList);
		}
	};

	const newTarget = new Proxy(originTarget.prototype.constructor, handler);

	return newTarget;
};
```

**Comment by kuitos** [comment]
1. 你要拿原构造函数的什么信息？
2. 框架注入依赖时只会处理目标函数声明的依赖，没办法处理父类的依赖啊。 Proxy 的方式也解决不了吧？
3. Proxy 不失为另一种解决方案，但是做这种框架底层服务时存在一些细节上的问题。比如 proxy 实例不能调用toString，而这是ng分析依赖的根本，等等。当然你可以试试看，也可能是年代久远我记忆缺失😂

**Comment by hjzheng** [comment]
@kuitos  
第1个目前还没有需求，但是我想至少返回新的 class 的话，对于一个 class 上加多个装饰器的情况，其他装饰器是拿不到原 constructor 的。 
第2个问题， 没有用 proxy 解决，只是将父类的 $inject 拿过来，扔到子类 $inject 里
第3个问题很关键啊。proxy实例 不能 toString 啊！My God 看来这样风险很大，我研究下。

**Comment by hjzheng** [comment]
大致翻了一下源码，对于没有 $inject 属性的函数需要进行 toString 分析依赖，问题应该不大吧！其它的就不知道了。看来还是要谨慎使用啊。

**Comment by kuitos** [comment]
1. 现在的实现，会 copy 原构造函数的静态属性给返回的 class，你要的信息能拿到
2. 如果要做这种事情，需要去一层层分析原型链，找出每一层构造函数的依赖列表。然后：
   1. 将所有父级的依赖列表 concat 到目标class 上，然后统一由目标 class 初始化。这样做简单但是不符合 extends 的行为语义。
   2. 符合语义的做法是，将每一层的父类单独初始化绑定到前一个类的prototype上，实现上问题很多比如这样被继承的类只能注入全局的服务，临时服务无法注入。问题很多几乎不可行。
   3. 最主要的是，前端开发中，组合 > mixin > 继承。耦合由低到高，继承几乎是最不可取的做法。
3. 记忆中 proxy 的问题不止 toString，在框架下用 proxy 风险很多，不过具体你可以试下。
