### ISSUE TITLE
有一个疑问

### ISSUE THREAD

**Issue by dcy0701** [kuitos/angular-es-utils#9]
injector的写法上。
当我先注册了component，最后调用了angular.bootstrap(document,['ahahah'])
这样子是无法在指令中获取到injector的。

**Comment by kuitos** [comment]
能否提供一个 [jsfiddle](https://jsfiddle.net/) 的重现demo？

**Comment by dcy0701** [comment]
@kuitos sry，忽略了动态输出的部分。
所以一直取不到injector。
可以close了，谢谢思路
